name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo build --release

      - run: cp target/release/altshift.exe altshift.exe

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: altshift.exe
          generate_release_notes: true
